apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-rollouts

resources:
- argo-rollouts-ns.yaml
- cert-cm.yaml
- https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml
- namespace-role.yaml

# Use custom image with AI plugin
images:
- name: quay.io/argoproj/argo-rollouts
  newName: ghcr.io/carlossg/rollouts-plugin-metric-ai
  newTag: latest

## This is needed becuase Argo Rollouts doesn't support adding CA info on the Prometheus provider
## see: https://github.com/argoproj/argo-rollouts/issues/2298
patchesStrategicMerge:
- add-ca-to-rollouts.yaml
- plugin-config-patch.yaml
- rbac-patch.yaml
